version: "3"
services:
  python-flask-nginx:
    image: tiangolo/uwsgi-nginx-flask:python3.6
    ports:
      - 8080:80
    volumes:
      - ./src:/app
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=80'
    command: flask run --host=0.0.0.0 --port=80