## COMMON ##
USERNAME = 'username'
PASSWORD = 'password'
ROLE = 'role'
OWNER = 'owner'
DATA = 'data'
TOKEN = 'token'

## ROLES ##
ADMIN = 'admin'
REPRESENTATIVE = 'representative'
COMPANY = 'company'
CONSUMER = 'consumer'

## DATA ##
CATEGORY = 'category'
ID = '_id'
SUB = 'sub'
JWT = 'jwt'
NAME = 'name'
DESCRIPTION = 'description'
SUBCATEGORY = 'subcategory'
PRODUCTNO = 'productNo'
CREATEDBY = 'createdBy'
PRODUCER = 'producer'
COMPANIES = 'companies'
USERS = 'users'
FILES = 'files'
MATERIAL_ID = 'material_id'
FILE_TIME = 'file_time'
FILE_NAME = 'file_name'
PATH = 'path'
RATES = 'rates'
RATE = 'rate'
VOTES = 'votes'
COMMENTS = 'comments'
AVERAGE = 'average'


## ROUTES ##
AUTH = 'auth'
ANNOTATIONS = 'annotations'
PRODUCTS = 'products'
COMPANIES = 'companies'
CONSUMERS = 'consumers'
REPRESENTATIVES = 'representatives'
ADMINS = 'admins'
MATERIALS = 'materials'
CATEGORIES = 'categories'
ENTRY = 'entry'
SELF = 'self'
ROOT = '/'

## RESPONSE ##
MESSAGE = 'message'
STATUS = 'status'
